version: '3.4'

services:
  browser:
    container_name: "docker-vnc-browser"
    environment:
      TZ: "Europe/Moscow"
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - "5900:5900"
    restart: on-failure
